WINDOW_TITLE = "Arcturus"

SCREEN_WIDTH = 96
SCREEN_HEIGHT = 54

VIEWPORT_WIDTH = int(SCREEN_WIDTH * 0.79)
VIEWPORT_HEIGHT = int(SCREEN_HEIGHT * 0.75)

STATUS_WIDTH = SCREEN_WIDTH - VIEWPORT_WIDTH - 3
STATUS_HEIGHT = SCREEN_HEIGHT // 3

ENTITY_WIDTH = SCREEN_WIDTH - VIEWPORT_WIDTH - 3
ENTITY_HEIGHT = SCREEN_HEIGHT - STATUS_HEIGHT - 3

BAR_WIDTH = STATUS_WIDTH - 2

LOG_WIDTH = VIEWPORT_WIDTH
LOG_HEIGHT = SCREEN_HEIGHT - VIEWPORT_HEIGHT - 3

MAP_WIDTH = 75
MAP_HEIGHT = 75

ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 6
MAX_ROOMS = 10000

FOV_ALGO = 0
FOV_LIGHT_WALLS = True
FOV_RADIUS = 10